compatible SharpRaven to .net 2.0
getsentry/raven-csharp pull request #274
Opened 2018-10-13 09:38 UTC by ArthurRen

1. Add genric deleagte : Func
2. Add TimeZomeInfo class , reference : https://www.codeproject.com/Articles/26727/How-to-use-time-zones-in-NET-under-Windows
3. Add extension method : Enumerable class & ExtensionAttribute

2018-10-22 07:50 UTC, bruno-garcia commented
@ArthurRen There are quite a few failing tests though. Could you please get the builds fixed?
Other then that, LGTM.

Would be great to get some feedback from @asbjornu

2018-10-22 07:50 UTC, bruno-garcia commented
@ArthurRen There are quite a few failing tests though. Could you please get the builds fixed?
Other then that, LGTM.

Would be great to get some feedback from @asbjornu

2018-10-22 10:02 UTC, asbjornu requested changes
Thanks for this!

I'm not sure this is the right direction to move the SharpRaven library in, though, since [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) is the forward looking library @getsentry is focusing on. That library already has .NET Core 2.0 support, doesn't it, @bruno-garcia? On top of that, [.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/), so 2.1 seems like a more forward-looking target.

Also, the tests are failing, so those need to be fixed before anything can be merged. I have a few comments on the naming and formatting, but otherwise this looks good.

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/Data/BackgroundRequester.cs
> +﻿#if !NET40 && !NET35 && !NET20
`NET20` is ambigous. If we introduce a compile time flag for .NET Core, I would prefer if it was named `NETCORE20` or `NETSTANDARD20` and then we should probably rename all of the old flags to `NETFX` for consistency and to be explicit.

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/Data/BackgroundRequester.cs
> +﻿#if !NET40 && !NET35 && !NET20
`NET20` is ambigous. Does it mean .NET Framework 2.0 or .NET Standard 2.0? If we introduce a compile time flag for .NET Core, I would prefer if it was named `NETCORE20` or `NETSTANDARD20` and then we should probably rename all of the old flags to `NETFX` for consistency and to be explicit.

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/Data/HttpRequestBodyConverter.cs
> +#if NET35 || NET20
It seems like the consistent way to have compile time flags is to align them with the context and not with the left margin. I don't care where they are placed, I just want it to be consistent. :)

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/Data/HttpRequestBodyConverter.cs
> +#if NET35 || NET20
It seems like the consistent way to have compile time flags in the solution is to align them with the context and not with the left margin. I don't care where they are placed, I just want it to be consistent. :)

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/SharpRaven.csproj
> +    <Configurations>Debug;Release;Debug-net20;Release-net20;Debug-net35;Release-net35;Debug-net40;Release-net40;Debug-net45;Release-net45;Debug-net471;Release-net471;Release-netstandard2.0;Debug-nets
Same comment applies here; the name should be `netcore20` or `netstandard20`.

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/Utilities/CircularBuffer.cs
> +        private class ConcurrentQueue<TElement> : ICollection, IEnumerable<TElement>
Is this change from `T` to `TElement` necessary?

2018-10-22 10:02 UTC, asbjornu commented on src/app/SharpRaven/Utilities/CircularBuffer.cs
> +        private class ConcurrentQueue<TElement> : ICollection, IEnumerable<TElement>
Is this change from `T` to `TElement` necessary?

2018-10-22 10:03 UTC, asbjornu reviewed
[.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/) and [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) already has .NET Core 2.0 support, so I'm not sure this pull request has much value, sorry.

2018-10-22 10:04 UTC, asbjornu commented
[.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/) and [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) already has .NET Core 2.0 support, so I'm not sure this pull request has much value, sorry.

2018-10-22 10:08 UTC, asbjornu requested changes
[.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/) and [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) afaik already has .NET Core 2.0 support, so I'm not sure this PR is necessary?

For this to be merged, I would want the following to change:

- Target 2.1 instead of 2.0
- Fix my review comments on naming, ambiguity and consistency.
- Ensure the build is successful.

If that is taken care of, this would have 👍 from me. 😃

2018-10-22 10:09 UTC, asbjornu requested changes
Thanks for this!

I'm not sure this is the right direction to move the SharpRaven library in, though, since [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) is the forward looking library @getsentry is focusing on. That library already has .NET Core 2.0 support, doesn't it, @bruno-garcia? On top of that, [.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/), so 2.1 seems like a more forward-looking target.

Also, the tests are failing, so those need to be fixed before anything can be merged. I have a few comments on the naming and formatting, but otherwise this looks good.

2018-10-22 10:47 UTC, asbjornu requested changes
Thanks for this!

I'm not sure this is the right direction to move the SharpRaven library in, though, since [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) is the forward looking library @getsentry is focusing on. That library already has .NET Core 2.0 support, doesn't it, @bruno-garcia? On top of that, [.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/), so 2.1 seems like a more forward-looking target.

Also, the tests are failing, so those need to be fixed before anything can be merged. I have a few comments on the naming and formatting, but otherwise this looks good.

2018-10-22 11:40 UTC, asbjornu requested changes
Thanks for this!

I'm not sure this is the right direction to move the SharpRaven library in, though, since [sentry-dotnet](https://github.com/getsentry/sentry-dotnet) is the forward looking library @getsentry is focusing on. That library already has .NET Core 2.0 support, doesn't it, @bruno-garcia? On top of that, [.NET Core 2.0 reached end of life October 1st](https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/), so 2.1 seems like a more forward-looking target.

Also, the tests are failing, so those need to be fixed before anything can be merged. I have a few comments on the naming and formatting, but otherwise this looks good.

2018-10-22 16:40 UTC, ArthurRen commented
Sorry , i'm busy with work recently , i will check out these problems at
this weekend.

Bruno Garcia <notifications@github.com> 于2018年10月22日周一 下午4:06写道：

> @ArthurRen <https://github.com/ArthurRen> There are quite a few failing
> tests though. Could you please get the builds fixed?
> Other then that, LGTM.
>
> Would be great to get some feedback from @asbjornu
> <https://github.com/asbjornu>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getsentry/raven-csharp/pull/274#issuecomment-431764083>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AkjR3ESJxu77ZOdCbAu51NsBzQNkHQOdks5unXx5gaJpZM4Xai8u>
> .
>

2018-10-23 08:21 UTC, bruno-garcia commented
@asbjornu That is correct that the [unified API SDK](https://github.com/getsentry/sentry-dotnet) supports .NET Core 2.0 and also its EOL. Please note that this PR is supposed to add support to .NET Framework 2.0 (2005).

Since the jump from the already supported .NET Framework 3.5 to 2.0 doesn't seem very big (as shows in the code change here) and requests to support 2.0 came 2 or 3 times. 

Also this change doesn't affect anyone using any version of .NET newer than 2.0 since the artifacts generated are split per version, I'd be OK with merging this in if you are. That is, if the builds are fixed.

2018-10-23 08:33 UTC, asbjornu commented
Aha, sorry. Yesterday was a bad day doing code reviews. I withdraw my comments minus the failing tests, then. If they are fixed, this LGTM.

2018-12-07 17:14 UTC, closed without merging